### ISSUE TITLE
Cloud events are only detected if the type begins with dev.knative

### ISSUE THREAD

**Issue by slinkydeveloper** [openshift-cloud-functions/faas-js-runtime#2]
When i try to use `context.cloudevent`, it returns undefined. After further investigation, i've found that the cloudevent is parsed only if the event type starts with `dev.knative`. There is any reason for this?

**Comment by zroubalik** [comment]
@lance yeah you are right, I wasnt aware of the knative event registry docs.

We can remove that part for surel
