### ISSUE TITLE
Use a web framework rather than raw Node.js http module

### ISSUE THREAD

**Issue by lance** [openshift-cloud-functions/faas-js-runtime#3]
Our framework currently just uses raw `http` modules from Node.js core. We might consider using an existing framework - perhaps one optimized for speed such as [Fastify](https://www.fastify.io).

**Comment by lance** [comment]
@slinkydeveloper Fastify is [as fast or faster than raw HTTP](https://github.com/fastify/fastify#benchmarks), and in refactoring the code to use it, I found that it was all a bit leaner, and provides a framework on which we can build and add features if necessary. The routing is less of a concern than just handling the requests, logging and other standardizing choices we would need to make. Using a framework makes these choices for us in many cases.

**Comment by slinkydeveloper** [comment]
Ok no problem, just let's try to keep the dependencies as less as possible... More dependencies means more build time, that's why i'm worried

**Comment by lance** [comment]
Yes, I agree with you re: build time. It is definitely something to keep an eye on.
